### PR TITLE
+ add simple debug messages for django(pongo2) template engine

### PR DESCRIPTION
**Pull request by absinsekt**
Django(Pongo2) template engine has nontransparent behaviour in case of markup errors.
We receive «[IRIS TEMPLATES] Template with name ... doesn't ex
ists in the dir». The template actually exists, but is buggy.

### CODE REVIEW

**Comment by kataras** [comment]
This is a nice idea but I can't approvei t as it is, because, on the render method this template will actually render succesfuly without error message or log, but the client would be able to see the complete error message, this is not secure way.

Recommendation: Edit the `config.go` add a `DebugTemplates bool` or something like that and re-pull, thanks you!!

**Comment by kataras** [comment]
This is a nice idea but I can't approve as it is, because, on the render method this template will actually render succesfuly without error message or log, but the client would be able to see the complete error message, this is not secure way.

Recommendation: Edit the `config.go` add a `DebugTemplates bool` or  `ParseOnError` something like that and re-pull, thanks you!!

**Comment by absinsekt** [comment]
Done

**Comment by kataras** [comment]
Excellent, thank you very much, keep going!!

**Pull request merged**
