### PR TITLE
html template partial file related to parent file's directory

### PR DESCRIPTION
**Pull request by syklevin**

### CODE REVIEW

**Comment by kataras** [comment]
I think that, this will break most up-and running iris servers, also there is no need to do something like that, we have examples for partials

**Comment by syklevin** [comment]
I could see your point. 
How about add another template func for that?
What i want to achieve actually is to load seperated css/js files base on current page, 
for example in my layout.html

<html>
<head>
{{ yield_script ".css" }}
</head>
<body>
{{ yield }}
<script src="/assets/javascripts/jquery.min.js"></script>
<script src="/assets/javascripts/modernizr.min.js"></script>
{{ yield_script ".js" }}
</body>
</html>

and the templates folder structure would be like these

templates
|- users
  |- index.html
  |- index.css.html
  |- index.js.html
  |- edit.css.html
  |- edit.html
  |- edit.js.html

**Comment by kataras** [comment]
Yes you can add a new func if you like, something like `partial_r` (partial relative) ?

**Comment by syklevin** [comment]
code updated, please take a look :)

**Comment by kataras** [comment]
Thanks, approved :)

**Comment by kataras** [comment]
Thanks, approved  :) *although you could do this for all template engines but I will do it someday if you don't have much time

**Pull request merged**
